steps:
  - command: ".buildkite/build.sh"
    label: ":hammer: Build"
    artifact_paths:
        - "MUXSDKStats.xcframework.zip"
    agents:
      queue: "iOS"
  - wait
  - command: "apps/TestApp/run-tests.sh"
    label: "Tests"
    agents:
      queue: "iOS"
